### ISSUE TITLE
upgrade to 1.3.0

### ISSUE THREAD

**Issue by WouterLS** [rvleij/p1monitor#3]
Hi,

Is het makkelijk te upgraden naar versie 1.3.0 vanuit een docker pull?
https://www.ztatz.nl/p1-monitor-download-202106/

**Comment by rvleij** [comment]
Hoi, nee kan nog niet. Ik moet de image updaten eerst en daar ben ik nog niet aan toegekomen helaas. Ik bouw de images op een Mac en daar kan ik niet (makkelijk) het Linux image inladen, kost wat tijd dus. Ik ga ermeer aan de slag en close deze issue als ik weer up to date ben, waarschijnlijk in het weekend.

**Comment by rvleij** [comment]
I have now updated the docker image to 1.3.1, so a pull will update your stuff. :) Don't forget to follow the "usual" update procedure, so first "update" in the p1mon web interface, then "stop". After that the docker bit with stop, rm, pull and start again (see readme). That way you'll keep your data. 

I have now fixed my build environment, so I can be a bit faster with updates!

**Comment by WouterLS** [comment]
Thanks for responding and fixing it.
I can see that the code has been updated to support version 1.3.1.
However when i stop/rm/pull/start the latest image I keep getting 1.2.0.

What am I doing wrong?

**Comment by rvleij** [comment]
I see it too indeed. I would assume at this point that it's a bug in the original version, I'll get my spare Pi4 out and verify it. Because I never had 1.2.0 as a version, since I went for 1.1.something to 1.3.1. And we're not at 1.1 and also not at 1.3. So only thing that can have happened is a glitch in the "original" somehow? Would have to verify it with the original image, I'll get back to you about it, will try this week. Weird indeed.

**Comment by WouterLS** [comment]
Thanks, that would be really helpfull.

**Comment by WouterLS** [comment]
It seems not all files are updated correctly.
When i look at scripts/const.py  I can see it's version up to 1.2.0

**Comment by rvleij** [comment]
OK, great. Will have to check if this is also the case at the original version, because I didn't do anything specifically I just moved the files for. I'll see if there is a new version and then just upgrade to that one. Back from holidays now, so a little more time now I'm at home in the crap weather again.

**Comment by rvleij** [comment]
OK, I've verified now, the Pi4 I run this card on has the same 1.2.0 in /scripts/const.py, so the image was baked correctly. I'm afraid this is a problem on the card image. I'll re-burn the image and restart the Pi, see if that changes anything. I was a bit afraid I had made a mistake while creating the docker image or updating the repo, like kept old files around or something. But so far it's an exact copy of what I'm running on my dev Pi4, it must be the same for the guys running the actual image.

**Comment by rvleij** [comment]
Found it, I must have switched memory cards or did something else stupid, because now it looks different and the correct version is displayed. I'll bake a new image and push to Docker repo as well. Thanks for persisting this and making me repeat all steps. I didn't see anyone on the project site reporting this, so it had to be me. :) Fix will be out in an hour or so, the cross build takes some time.
